### ISSUE TITLE
DPMM: Bad Gateway and 401 error on navigation between pages

### ISSUE THREAD

**Issue by Reikyo** [theodi/maturity.theodi.org#20]
After starting a project, I looked back on the projects dashboard to see what was there. Click "View Report" and see report summary. Click "Evaluations Dashboard" or "Back to edit page" to navigate to another page, then get Cloudflare "Bad Gateway" page. Reload page, then get generic "Service Unavailable" page. Reload page, then get ODI "401: Unauthorised" page. Have to click "Login" again which takes you back to "Authenticate with The ODI" page, and can then get back in to the dashboard.

**Comment by davetaz** [comment]
Also fixed in v1.0.1
